document.writeln("    <div class=\'container\'>");
document.writeln("      <!-- 导航条 -->");
document.writeln("      <div class=\'col-md-12\'>");
document.writeln("        <div class=\'navigation\'>");
document.writeln("          <nav class=\'navbar navbar-inverse navbar-fixed-top\'>");
document.writeln("            <div class=\'container-fluid\'>");
document.writeln("              <!-- Brand and toggle get grouped for better mobile display -->");
document.writeln("              <div class=\'navbar-header\'>");
document.writeln("                <button type=\'button\' class=\'navbar-toggle collapsed\' data-toggle=\'collapse\' data-target=\'#bs-example-navbar-collapse-1\' aria-expanded=\'false\'>");
document.writeln("                  <span class=\'sr-only\'>Toggle navigation</span>");
document.writeln("                  <span class=\'icon-bar\'></span>");
document.writeln("                  <span class=\'icon-bar\'></span>");
document.writeln("                  <span class=\'icon-bar\'></span>");
document.writeln("                </button>");
document.writeln("                  <a class=\'navbar-brand\' href=\'gbook.php\'>");
document.writeln("                    <img alt=\'Jave\' src=\'img/brand1.ico\'>");
document.writeln("                    <span>Jave</span>");
document.writeln("                  </a>");
document.writeln("              </div>");
document.writeln("              <div class=\'collapse navbar-collapse\' id=\'bs-example-navbar-collapse-1\'>");
document.writeln("                <ul class=\'nav navbar-nav\'>");
document.writeln("                  <li class=\'active\'><a href=\'gbook.php\'>首页 <span class=\'sr-only\'>(current)</span></a></li>");
document.writeln("                  <li><a href=\'gbook.php\'>个人展示</a></li>");
document.writeln("                </ul>");
document.writeln("                <form class=\'navbar-form navbar-left form-group-sm\'>");
document.writeln("                  <div class=\'form-group\'>");
document.writeln("                    <input type=\'text\' class=\'form-control\' placeholder=\'使用用户名进行查询\'>");
document.writeln("                  </div>");
document.writeln("                  <button type=\'submit\' class=\'btn btn-default btn-sm\'>搜索</button>");
document.writeln("                </form>");
document.writeln("                <ul class=\'nav navbar-nav navbar-right\'>");
document.writeln("                    <li><a href=\'login.html\'>登录</a></li>");
document.writeln("                    <li class=\'dropdown\'>");
document.writeln("                      <li><a href=\'register.php\'>注册</a></li>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("              </div><!-- /.navbar-collapse -->");
document.writeln("            </div><!-- /.container-fluid -->");
document.writeln("          </nav>");
document.writeln("          </div>");
document.writeln("      </div>");
document.writeln("    </div>");
