document.writeln("    <div class=\'container\'>");
document.writeln("      <!-- 脚注 -->");
document.writeln("      <div class=\'col-md-12\'>");
document.writeln("        <div class=\'navigation\'>");
document.writeln("          <nav class=\'navbar navbar-inverse navbar-fixed-bottom\'>");
document.writeln("            <div class=\'footer\'>");
document.writeln("              <span>Copyright © 2018 Jave学习独立开发 All Rights Reserved</span></br>");
document.writeln("              <span>本留言版资源均为原创，免费转载请保留版权信息，严禁商业转载。</span>");
document.writeln("            </div>");
document.writeln("          </nav>");
document.writeln("          </div>");
document.writeln("      </div>");
document.writeln("    </div>");
